### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by josefkorbel** [crucialfelix/django-ajax-selects#237]
Hello, is this still maintaned? I've came across some errors out of the box.

```
File "/usr/local/lib/python3.6/site-packages/ajax_select/fields.py", line 209, in render
    values = list(value)
TypeError: 'int' object is not iterable
```

I just literally did everything according to tutorial. No idea here cause the traces arent clear.

**Comment by crucialfelix** [comment]
There was a release just 6 days ago, though I did forget to push the version bump to github (just did it).

If you got that error then you were using a AutoCompleteSelectMultipleWidget:  https://github.com/crucialfelix/django-ajax-selects/blob/5488b26c5e2137dc7e5155ec740406589f02e512/ajax_select/fields.py#L209

but the value passed in was an `int` which suggests that you may have used a AutoCompleteSelectMultipleField (form field) on a ForeignKey (model field). Because instead of getting a list of ints it got a single int.

Which tutorial did you literally copy from ?  Can you post the code you are actually using ?

**Comment by josefkorbel** [comment]
Hello @crucialfelix,
Thanks for your fast input, you're right. I managed to make it run now, but I am having visual misaligment, did I mess something up? 
![device](https://user-images.githubusercontent.com/20358070/44789666-74a53780-ab9d-11e8-8acc-8879a2cad26e.JPG)

**Comment by josefkorbel** [comment]
I fixed this by turning this
```
form .aligned .results_on_deck {
  padding-left: 38px;
  margin-left: 7em;
}
```
into this
```
form .aligned .results_on_deck {
  padding-left: 38px;
  margin-left: 10em;
}
```
However that is not ideal way of fixing this issue.

**Comment by crucialfelix** [comment]
Django's admin styling isn't very cooperative. I wonder if it's changed. What django version  ?

**Comment by josefkorbel** [comment]
Hello @crucialfelix 
Django version I am using is `2.1.0`.
