### ISSUE TITLE
Dynamically change source URL?

### ISSUE THREAD

**Issue by chrisspen** [crucialfelix/django-ajax-selects#263]
How do you dynamically add parameters to the source URL from client-side Javascript?

I'm trying to do something similar to issue #231, except completely client-side. I have a "region" dropdown using ajax-select and in order to narrow down the items it shows, I want to add a `category=<value>` URL parameter to the source URL when the user selects a separate "category" dropdown. Each region is associated with a category, so by passing that in the URL, I can read that inside my lookup and use it to filter the number of items returned.

I see the plugin-options are set in a data attribute, but if I try to do something like this in my template:

    $('#category').change(function(){
        var cat = $(this).val(); 
        $('#my_region').data('plugin-options', {"source": "/lookups/region?category="+cat, "html": true})
    });

it doesn't seem to do anything, and  still uses the default source URL.

**Comment by chrisspen** [comment]
I think I found a way to hack this, but there are a few bugs in the core JQuery plugin that make this a little difficult.

It looks like you cloned the autocomplete plugin, but you're using a very old version, and so most of the [official API](https://api.jqueryui.com/autocomplete/#option-source) doesn't work with your code, so we can't do things like simply call `$(selector).autocomplete('option', 'source', some_new_source)`.

However, I found if I directly override the data-plugin-options value, kill the plugin, and then re-initialize, this successfully changes the source URL. e.g.

    $(selector).attr('data-plugin-options', '{"source": "my/new/path?category="+some_value, "html": true}');
    $(selector).autocompleteselectmultiple('destroy');
    $(selector).data('_ajax_select_inited_', false); // yes, the destroy method doesn't do this for you, yet this is required by the init method
    $(window).trigger('init-autocomplete');

**Comment by crucialfelix** [comment]
Yes, it is a very old version. Rather than rewrite this to use the new one, I think it's better to migrate to a more modern UI solution. That essentially means making a different project than this one. This is a glue solution. It glues two technologies together and suffers the pain of upgrades and compatibility conflicts.

You could maybe use a custom source URL and write a Django view that handles contextual switching. Or swap in the frontend as you are doing. Whichever is less annoying.

fyi. I'm not cloning the plugin at all
