### ISSUE TITLE
cleaned_data from django-ajax-select returns ids but not objects

### ISSUE THREAD

**Issue by chrislo42** [crucialfelix/django-ajax-selects#271]
Hello,

When using django-ajax-selects for m2m related field, the django form always get that field changed because the initial value is the objects but the cleaned data is just ids of the objects.
So, each time the form is submitted, a new entry is created in the junction table of the m2m field.
Why return ids instead of objects ?

**Comment by crucialfelix** [comment]
I have never seen a new entry created every single time this is used, so I think you were experiencing something else. It returns ids because that is what the Django uses to identify the instance and store to the database.

The Django admin isn't exactly a frontend UI platform. It's just a basic admin for technical people to manage data. 

There is now finally some support in Django itself for what django-ajax-select solves, and there are some other packages that do this.
