### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'window.django.jQuery')

### ISSUE THREAD

**Issue by SukiCZ** [crucialfelix/django-ajax-selects#313]
Hi and thanks for an awesome library :smiley_cat: 

I've run into an issue when using `django-ajax-select` outside of Django Admin after upgrading to `3.0.1+`

![image](https://github.com/crucialfelix/django-ajax-selects/assets/7142785/3db92b3c-e869-4375-920f-03a63629df82)

The issue is `Uncaught TypeError: Cannot read properties of undefined (reading 'jQuery')` as `window.django` is undefined. Issue can be reproduced with the `/example` folder.

The issue can be fixed by including a [admin/js/jquery.init.js](https://github.com/django/django/blob/4.2.10/django/contrib/admin/static/admin/js/jquery.init.js) to `form.media`.

**Comment by crucialfelix** [comment]
My apologies, it's been an extremely busy year and I did not even notice this notification!

The code does assume that it's in the admin, and it shouldn't.

But rather than include the admin jquery when you aren't actually in the admin, it should simply not depend on that window.django.jQuery

https://github.com/crucialfelix/django-ajax-selects/blob/e3c8df673ef7d0487ce4b9c456ee8c81976bac4e/ajax_select/static/ajax_select/js/ajax_select.js#L234-L255

The init should be 
```js
(window.jQuery, window.django && window.django.jQuery);
```
so that it doesn't throw an error.

The call to `djangoJQuery(document) ` should only happen if djangoJQuery is set.

```js
if(djangoJQuery) {
   djangoJQuery(document)  etc....
   
  }
```

Does that make sense? The reason to pass in the django jquery is only to initialize ) dismissAddRelatedObjectPopup which only happens if you are in the django admin.

Again I apologize for the really late response! I've just been drowned in work all year long.

**Comment by SukiCZ** [comment]
@crucialfelix Thanks for your explanation and suggestion, which has been implemented.

No worries for the wait. I'm glad you found the notification anytime later :blush:
