### ISSUE TITLE
DeprecationWarning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated

### ISSUE THREAD

**Issue by misalabs** [crucialfelix/django-ajax-selects#96]
I'm getting the following Warning for TheForm:

$python manage.py validate          
../local/lib/python2.7/site-packages/ajax_select/__init__.py:92: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form TheForm needs updating
  class TheForm(superclass):

That happens in Django 1.7

**Comment by pzrq** [comment]
As `RemovedInDjango18Warning ` suggests, this breaks with Django 1.8 alpha 1. 
https://www.djangoproject.com/weblog/2015/jan/16/django-18-alpha-1-released/

A hacky quick fix would be to:

    class TheForm(superclass):
        class Meta:
            exclude = ()

**Comment by misalabs** [comment]
Totally agree!

**Comment by pzrq** [comment]
Looked a bit deeper, my earlier version is definitely a hack. Recall that the goal here is to handle potential Mass Assignment Vulnerabilities:
https://docs.djangoproject.com/en/1.6/releases/1.6/#modelform-without-fields-or-exclude
http://en.wikipedia.org/wiki/Mass_assignment_vulnerability

Since `TheForm` is already pulling in `fields`, `exclude` and `widgets` from a provided `superclass.Meta`, this should only happen if the developer passed `fieldlist={}` or similar and their ModelForm superclass hasn't got `fields` or `exclude` either.
https://github.com/mathspace/django-ajax-selects/blob/develop/ajax_select/__init__.py

Considering that, it would be nice if there was a clearer error message for Django >= 1.8

**Comment by pzrq** [comment]
Note that it has been fixed on master with `__all__`:
https://github.com/crucialfelix/django-ajax-selects/commit/6f12ba65440ab65356c7113b7af2ad5dc4ed10b6

Not sure if that can be exploited as `TheForm` is really just to query for data, if I can find a way to exploit it then something like the following will be needed:
https://github.com/crucialfelix/django-ajax-selects/compare/develop...mathspace:develop

**Comment by pzrq** [comment]
@crucialfelix @misalabs 
Recommend closing in favour of the `fields = '__all__'` fix on `develop` (sorry I earlier incorrectly stated it was on `master`). I cannot see a way to create a mass assignment vulnerability using `make_ajax_form()` as I can only see it used to read existing data.

Getting a new `pip` tagged/installable version sooner rather than later would be awesome.

For info, Django 1.8 final is expected around April 1 (not sure if that's a joke or not):
https://www.djangoproject.com/weblog/2015/mar/18/security-releases/

**Comment by misalabs** [comment]
Django 1.8 wasn't a joke.

**Comment by jonathanmorgan** [comment]
Sorry for creating duplicate in #115.  Any idea when you might be able to get the latest up into pypi?  In the interim, should I just download the current contents of the repository to the package's folder in site-packages?

**Comment by pzrq** [comment]
@jonathanmorgan From memory you can install a specific commit by cloning the git repo with something like:

pip install -e git+https://github.com/crucialfelix/django-ajax-selects.git@6f12ba65440ab65356c7113b7af2ad5dc4ed10b6#egg=django-ajax-selects-dev

Generally not recommended for production environments but fine if you're just developing and testing things.

**Comment by crucialfelix** [comment]
I'm doing the new release today.

**Comment by jonathanmorgan** [comment]
I'll make note of how to use git for a specific commit, but if the release is coming today, I'll just wait for that.

thank you, and thank you!

**Comment by crucialfelix** [comment]
Its out now https://pypi.python.org/pypi/django-ajax-selects

**Comment by jonathanmorgan** [comment]
Works great for me on all the sites I control that use it (only three, but much appreciated!).

**Comment by pzrq** [comment]
Thanks @crucialfelix !
